
name: Deploy Bunny Scripting Script

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install
        run: "npm install && npm run db:push && npm run db:generate"

      - name: Build
        run: "npm run build && npm start"

      - name: Publish the script to Bunny
        uses: "BunnyWay/actions/deploy-script@main"
        with:
          script_id: 57289
          file: "dist/index.js"
